config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    registrations: 'members/registrations'
  }
  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#new_guest'
  end
  resources :movies, only: [:index, :show, :edit, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :members, only: [:show, :edit, :update, :destroy]
  get 'inquirys/new' => 'inquirys#new'
  post 'inquirys/confirm' => 'inquirys#confirm'
  post 'inquirys/done' => 'inquirys#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'homes#top'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :review
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 30 }
  validates :message, presence: true, length: { maximum: 200 }
end

app/models/ivent.rb
class Ivent < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  #mount_uploader :image_id, ImageUploader

  enum role: { member: 0, admin: 1 }
  validates :name, presence: true, length: {maximum: 20, minimum: 1, allow_blank: true}
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。', allow_blank: true}

  #ゲストユーザーの作成
  def self.guest
    find_or_create_by!(name:'ゲスト', name_kana:'ゲスト', email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  has_many :reviews, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :member
  belongs_to :movie
  has_many :favorites, dependent: :destroy
#0.5から5段階の間の評価になるよう設定
  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5
  }, presence: true

  validates :title, presence: true
  validates :content, presence: true

  def favorited_by?(member)
		favorites.where(member_id: member.id).exists?
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :movies, through: :tag_relationships
  validates :tag_name, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to member_path(@member), notice: "編集内容を保存しました。"
    else
      render :edit
    end
  end


  private
  def member_params
    params.require(:member).permit(:name, :name_kana, :image, :introduction)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])

  end


  private
  def movie_params
    params.require(:movie).permit(:title, :introduction, :image_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.member_id = current_member.id
    @review.movie_id = @movie.id
    if @review.save
      redirect_to movie_path(@review.movie)
    else
      render :new
    end
  end


  def edit
    @movie = Movie.find(params[:id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to movie_path(@review.movie)
    else
      render :edit
    end
  end

  def destroy
  end


  def review_params
    params.require(:review).permit(:title, :content, :score)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>shareKinoへようこそ！</h1>
    <p>shareKinoでは、映画のレビューを共有することができます！</p>
    <p>まずは使ってみましょう！</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to '会員登録', new_member_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>

      <br><p>既に会員の方はこちらから</p>
      <div class="row">
        <p><%= link_to 'ログイン', new_member_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>

      <br><p>ゲストとしてログインしたい方はこちらから</p>
      <div class="row">
        <p><%= link_to 'ゲストログイン（閲覧用）', members_guest_sign_in_path, method: :post, class: "btn btn-warning col-xs-10 col-xs-offset-1" %></p>
      </div>

    </div>

  </div>
</div>

app/views/movies/index.html.erb
<div class="col-xs-offset-2 col-xs-7 movie_index">
  <h4 class="text-center movie_index">映画一覧</h4>
  <!-- col-xs-9の中を更に4等分する -->
  <div class="row">
    <% @movies.each do |movie| %>
    <div class="col-xs-4 movie-image">
      <%= image_tag movie.image_id_url(:thumb) if movie.image_id.present? %><br>
      <%= link_to movie.title.truncate(16), movie_path(movie) %>
    </div>
    <% end %>
  </div>

app/views/movies/show.html.erb
<div class="row">
	<div class="text-center col-xs-9 col-xs-3-offset movie-image">
    <%= image_tag @movie.image_id.url, width: '200px' if @movie.image_id.present? %><br>
		<%= @movie.title %><br>
		<%= @movie.introduction %><br>
		<%= link_to "レビューを作成", new_movie_review_path(@movie) %>
	</div>
</div>

<h3 class="text-center">レビュー一覧</h3>
	<% @movie.reviews.each do |review| %>
<div class="row">
	<div class="col-xs-3 review-members">
		<%= attachment_image_tag(review.member, :image, :fill, 80, 80, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg") %><br>
		<%= link_to review.member.name, member_path(review.member) %>さん<br>
	</div>
	<div class="col-xs-9 review-posts">
		<%= review.title %>
		<%= render "favorites/favorite-btn", review: review %>
		<%= render "reviews/star", review: review %>
		<%= review.content %><br>
		<div class="col-md-12 edit-button">
       <% if current_member == review.member %>
         <%= link_to 'レビューを編集', edit_movie_review_path(review), class:'btn btn-success' %>
         <%= link_to 'レビューを削除', movie_review_path(review), method: :delete, class:'btn btn-danger' %>
       <% end %>
    </div>
	</div>
</div>
<% end %>

app/views/reviews/_star.html.erb
<div id="star-rate-<%= review.id %>"></div>
    <script>
	    $('#star-rate-<%= review.id %>').raty({
		    size: 36,
	      starOff:  '<%= asset_path('star-off.png') %>',
	      starOn : '<%= asset_path('star-on.png') %>',
	      starHalf: '<%= asset_path('star-half.png') %>',
	      half: true,
	      readOnly: true,
	      score: <%= review.score %>,
	    });
    </script>

app/views/reviews/edit.html.erb
<%= form_for [@movie, @review] do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="col-md-6 col-md-offset-3">

        <h3>レビュー編集</h3>

        <%= f.label :title %><br>
        <%= f.text_field :title, :class => "form_control" %>

            <div class="field" id="star">
                <%= f.label :score %><br>
                <%= f.hidden_field :score, id: :review_star %>
            </div>
        <%= f.label :content %>
        <%= f.text_area :content, :class => "form-control", :size => "50x20"  %><br>
        <%= f.submit "レビュー評価", :class => "btn btn-primary" %>

    </div>


    <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'review[score]',
          half: true,
        });
    </script>

<% end %>

app/views/reviews/new.html.erb
<%= form_for [@movie, @review] do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="col-md-6 col-md-offset-3">

        <h3>レビュー投稿</h3>

        <%= f.label :title %><br>
        <%= f.text_field :title, :class => "form_control" %>

            <div class="field" id="star">
                <%= f.label :score %><br>
                <%= f.hidden_field :score, id: :review_star %>
            </div>
        <%= f.label :content %>
        <%= f.text_area :content, :class => "form-control", :size => "50x20"  %><br>
        <%= f.submit "レビュー評価", :class => "btn btn-primary" %>

    </div>


    <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'review[score]',
          half: true,
        });
    </script>

<% end %>