config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    registrations: 'members/registrations'
  }
  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#new_guest'
  end
  resources :movies, only: [:index, :show, :edit, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :members, only: [:show, :edit, :update, :destroy]
  get 'inquirys/new' => 'inquirys#new'
  post 'inquirys/confirm' => 'inquirys#confirm'
  post 'inquirys/done' => 'inquirys#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'homes#top'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :review
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 30 }
  validates :message, presence: true, length: { maximum: 200 }
end

app/models/ivent.rb
class Ivent < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  #mount_uploader :image_id, ImageUploader

  enum role: { member: 0, admin: 1 }
  validates :name, presence: true, length: {maximum: 20, minimum: 1, allow_blank: true}
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。', allow_blank: true}

  #ゲストユーザーの作成
  def self.guest
    find_or_create_by!(name:'ゲスト', name_kana:'ゲスト', email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  has_many :reviews, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :member
  belongs_to :movie
  has_many :favorites, dependent: :destroy
#0.5から5段階の間の評価になるよう設定
  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5
  }, presence: true

  validates :title, presence: true
  validates :content, presence: true

  def favorited_by?(member)
		favorites.where(member_id: member.id).exists?
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :movies, through: :tag_relationships
  validates :tag_name, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])

  end


  private
  def movie_params
    params.require(:movie).permit(:title, :introduction, :image_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_error_messages.html.erb
    	<% if model.errors.any? %>
    	  <div class="alert alert-danger">
      		<div id="error_explanation">
      			<ul>
      				<% model.errors.full_messages.each do |message| %>
      				<li><%= message %></li>
      				<% end %>
      			</ul>
      		</div>
      	</div>
    	<% end %>

app/views/layouts/_footer.html.erb
<div class="footer_inner">
  <div class="footer_box">
    <p>© shareKino</p>
    <p class="inquiry">お問い合わせは<%= link_to "こちら", inquirys_new_path %>から</p>
  </div>
</div>

app/views/layouts/_header.html.erb
  <h2 class="nav nav-pills navbar-left logo">
    <%= link_to root_path, class: "EDITlink" do %>
      <i class="fas fa-film"></i> shareKino
    <% end %>
  </h2>

<nav>
    <ul class="nav nav-pills navbar-right">
      <% if member_signed_in? %>
       <!--ログインしている時-->
        <li class="header-name">
          ようこそ、<%= current_member.name %>さん！
        </li>
        <li class="header-item">
          <%= link_to " mypage", member_path(current_member), class:"header_btn glyphicon glyphicon-user", :style=>"color:white; text-decoration:none;" %>
        </li>
        <li class="header-item">
          <%= link_to " movies", movies_path, class: "header_btn glyphicon glyphicon-film", :style=>"color:white; text-decoration:none;" %>
        </li>
        <li class="header-item">
          <%= link_to " log out", destroy_member_session_path, method: :delete, class: "header_btn glyphicon glyphicon-log-out", :style=>"color:white; text-decoration:none;" %>
        </li>
      <% else %>
      <!--ログインしていない時-->
        <li class="header-item">
          <%= link_to " movies", movies_path, class: "header_btn glyphicon glyphicon-film", :style=>"color:white; text-decoration:none;" %>
        </li>
        <li class="header-item">
          <%= link_to " sign up", new_member_registration_path, class: "header_btn glyphicon glyphicon-check", :style=>"color:white; text-decoration:none;" %>
        </li>
        <li class="header-item">
          <%= link_to " log in", new_member_session_path, class: "header_btn glyphicon glyphicon-log-in", :style=>"color:white; text-decoration:none;" %>
        </li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareKino</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body>
    <header class="header">
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <div class="row row-height">
        <%= yield %>
      </div>
    </div>
    <div>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>