config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    registrations: 'members/registrations'
  }
  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#new_guest'
  end
  resources :movies, only: [:index, :show, :edit, :destroy] do
    resources :reviews, only: [:new, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :members, only: [:show, :edit, :update, :destroy]
  get 'inquirys/new' => 'inquirys#new'
  post 'inquirys/confirm' => 'inquirys#confirm'
  post 'inquirys/done' => 'inquirys#done'
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'homes#top'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :review
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 30 }
  validates :message, presence: true, length: { maximum: 200 }
end

app/models/ivent.rb
class Ivent < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  #mount_uploader :image_id, ImageUploader

  enum role: { member: 0, admin: 1 }
  validates :name, presence: true, length: {maximum: 20, minimum: 1, allow_blank: true}
  validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。', allow_blank: true}

  #ゲストユーザーの作成
  def self.guest
    find_or_create_by!(name:'ゲスト', name_kana:'ゲスト', email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  has_many :reviews, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :member
  belongs_to :movie
  has_many :favorites, dependent: :destroy
#0.5から5段階の間の評価になるよう設定
  validates :score, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5
  }, presence: true

  validates :title, presence: true
  validates :content, presence: true

  def favorited_by?(member)
		favorites.where(member_id: member.id).exists?
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :movies, through: :tag_relationships
  validates :tag_name, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/inquirys_controller.rb
class InquirysController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :confirm
    else
      render :new
    end
  end

  def done
    @inquiry = Inquiry.new(inquiry_params)
    #:backパラメータを受け取ったら入力画面に戻る
    if params[:back]
      render :new
    #メール送信
    else
      InquiryMailer.send_mail(@inquiry).deliver_now
      render :done
    end
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[destroy]

  #2名以上ログイン時強制ログアウトされないようゲストユーザーを削除できないようにする
  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  def new_guest
    member = Member.guest
    sign_in member
    redirect_to movies_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to member_path(@member), notice: "編集内容を保存しました。"
    else
      render :edit
    end
  end


  private
  def member_params
    params.require(:member).permit(:name, :name_kana, :image, :introduction)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])

  end


  private
  def movie_params
    params.require(:movie).permit(:title, :introduction, :image_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.member_id = current_member.id
    @review.movie_id = @movie.id
    if @review.save
      redirect_to movie_path(@review.movie)
    else
      render :new
    end
  end


  def edit
    @movie = Movie.find(params[:id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to movie_path(@review.movie)
    else
      render :edit
    end
  end

  def destroy
  end


  def review_params
    params.require(:review).permit(:title, :content, :score)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/members/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(member, :image, size:"150x150", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg") %></tr>

	<tr>
		<th class="text-center"><%= member.name %></th>
	</tr>
	<tr>
		<th class="text-center"><%= member.introduction %></th>
	</tr>
</table>

<div class="row">
	<% if current_member == member %>
	<%= link_to 'ユーザー情報を編集する', edit_member_path(member), class: "col-xs-12 btn btn-success edit_member_#{member.id}" %>
	<% end %>
</div>

app/views/members/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h2>会員情報</h2>

    <%= form_with model:@member, local: true do |f| %>

    	<!-- エラーメッセージ表示-->
    	<%= render 'layouts/error_messages', model: f.object %>

    	<div class="field">
    		<%= f.label :image_id %>
    		<%= attachment_image_tag(@member, :image, size:"100x100", class: "img-circle pull-left profile-thumb", format: 'jpeg', fallback: "no_image.jpg") %>
    		<%= f.attachment_field :image, class: "member_image" %>
    	</div>


    	<div class="field">
    		<%= f.label :name %><br>
    		<%= f.text_field :name, class: "name" %>
    	</div>

    	<div class="field">
        <%= f.label :introduction %><br>
    		<%= f.text_field :introduction, class: "name" %>
    	</div>

    	<div class="actions">
    		<%= f.submit "編集内容を保存", class: "btn btn-danger" %>
    	</div>

    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User infomation</h2>
		<%= render 'members/profile', member: @member %>
	</div>
	<div class="col-xs-9">
		<h4 class="text-center movie_index">review一覧</h4>
		<!--review一覧 -->
		<% @member.reviews.each do |review| %>
			<div class="row">
				<div class="col-xs-3">
					<div class="movie-image">
						<%= image_tag review.movie.image_id.url ,width: '100px' %><br>
						<%= link_to review.movie.title, movie_path(review.movie_id) %><br>
					</div>
					<%= render "reviews/star", review: review %>
         	<br>
        </div>
        <div class="col-xs-9">
					<%= review.title %> |
				<td class="favorite-btn">
					<%= render "favorites/favorite-btn", review: review %>
				</td><br>
					<%= review.content %><br>
				</div>
			</div>
		<% end %>
		<!--review一覧 -->
	</div>
</div>